version: '3'
services:
  books-api:
    build: .
    environment:
      MONGO_URI: mongodb://mongoadmin:password@mongodb:27017
    ports:
      - 3002:3001
    volumes:
      - .:/app
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports: 
     - 27017:27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: mongoadmin
     MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
     ME_CONFIG_MONGODB_ADMINPASSWORD: password
     ME_CONFIG_MONGODB_SERVER: mongodb
    restart: unless-stopped